# -*- coding: utf-8 -*-
"""BayronBarra_004_A

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T6XFuIPdue2o-32tzc2P8CvyiXm-SofK
"""

plat=0
gold=0
silver=0
i=0
def menu():
    print('''Venta de Entradas
        1. Comprar Entradas
        2. Mostrar Entradas disponibles
        3. Ver listado de compradores
        4. Mostrar Ganancias Totales
        5. Salir''')

def comprar():
    while True:
        try:
            entrada_nueva = int(input("Ingrese cantidad de entradas"))
            if entrada_nueva >= 1 and entrada_nueva <= 3:
                break
            else:
                print("Ingresa un valor entre 1 y 3")
        except:
            print("Error")

    print("=== Puestos Disponibles ===")
    for i in range(1, 101):
            disp = i
            if i not in vendidos:
                print(f"Entrada: {i}")

    while True:
        try:

            posicion = int(input("Ingrese posicion que desea comprar "))
            if posicion >= 1 or posicion <= 20:
              plat+=1
              break
            elif posicion >=21 or posicion <=50:
              gold+=1
              break
            elif posicion >=51 or posicion <=100:
              silver+=1
              break

            else:
                print("Ingresa un valor entre 1 y 100")

        except:
            print("Error")

    while True:
        try:
            run = int(input("Ingrese el RUN del comprador sin puntos ni dígito verificador: "))
            if len(str(run)) == 8:
                break
            else:
                print("Largo de RUN erróneo")
        except:
            print("Error, recuerda ingresar solo dígitos")
    while True:
      if posicion in vendidos:
        print("La entrada que ingresó no está disponible.")
        break
      else:
        vendidos.append(posicion)
        comprador.append(run)
        print("La operación se ha realizado correctamente.")
        break

def mostrar_entradas_disponibles():
    print("=== Puestos Disponibles ===")
    for i in range(1, 101):
            disp = i
            if i not in vendidos:
                print(f"Entrada: {i}")

def mostrar_listado_compradores():
    print("=== Listado de Compradores ===")
    for i in range(len(comprador)):
        print(f"Posicion: {vendidos[i]}, RUN: {comprador[i]}")

def mostrar_ganancias_totales():
    total_ventas = plat*120000+gold*80000+silver*50000
    print(f"Las ganancias totales por concepto de ventas son: {total_ventas} UF")

# Variables globales
entradas_disponibles = ["1","2","3","4","5","6","7","8","9","10",
             "11","12","13","14","15","16","17","18","19","20",
             "21","22","23","24","25","26","27","28","29","30",
             "31","32","33","34","35","36","37","38","39","40",
             "41","42","43","44","45","46","47","48","49","50",
             "51","52","53","54","55","56","57","58","59","60",
             "61","62","63","64","65","66","67","68","69","70",
             "71","72","73","74","75","76","77","78","79","80",
             "81","82","83","84","85","86","87","88","89","90",
             "91","92","93","94","95","96","97","98","99","100",]
vendidos = []
comprador = []
precios = {"Platinum": 120000, "Gold": 80000, "Silver": 50000}

# CODIGO PRINCIPAL


while True:
    menu()
    op = input("Ingrese una opción: ")
    if op == "1":
        comprar()
    elif op == "2":
        mostrar_entradas_disponibles()
    elif op == "3":
        mostrar_listado_compradores()
    elif op == "4":
        mostrar_ganancias_totales()
    elif op == "5":
        print("Hasta luego")
        break
    else:
        print("Opción inválida. Por favor, seleccione una opción válida.")